### PR TITLE
Update EDSM url

### PR DESCRIPTION
**Pull request by AnthorNet**

### CODE REVIEW

**Comment by Marginal** [comment]
Ah I was already testing a patch to do the same thing - 75cf0d6
My version doesn't bother with the url lookup - it seems like extra work for the EDSM servers that will not be used much of the time ?

**Comment by AnthorNet** [comment]
Your version is cleaner indeed ^^
Note that I sent fromSoftware every time and added a fdId parameter to track Frontier Id.

**Comment by Marginal** [comment]
I've added fromSoftware in f239aec .
I will incorporate your fdId change.

**Comment by Marginal** [comment]
Have implemented the same thing in parallel in 75cf0d6 and f239aec , so closing.

**Pull request closed without merging**
